### ISSUE TITLE
abstract header and title should not be boldfaced

### ISSUE THREAD

**Issue by ElijahFromm** [acerjan/yale_phd_thesis_template#2]
To comply with current (2023) submission requirements, one must remove all instances of "\bf " from the .cls file.

**Comment by acerjan** [comment]
Thank you for letting me know. To confirm, you've otherwise used the template and had it accepted by the registrar's office, but this is the only needed change?

**Comment by ElijahFromm** [comment]
Yes, they accepted it with this change. Thank you for the template!

**Comment by acerjan** [comment]
Templated has been updated to reflect this change. Thank you!
